use <componentes.scad>

DIAMETRO_TUBO = 19;
LONGITUD_TUBO = 265+2*11+2*7;
ESPESOR_MINIMO = 4;
EXCESO_LONGITUDINAL = 2;
ANCHO_INTERNO_Y = 44;
ALTO_INTERNO_Z = 45;
ESPESOR_BASE = 8;
SEPARACION_BASE_TUBO = 5;
DISTANCIA_CUBRIR_TUBO = 11+7+10;
LUZ_TAPA_BASE = 1;
POSICION_ARRANCADOR_X = 220;
POSICION_REACTANCIA_X = 100;

module gabinete_base() {
    difference() {
        union() {
            translate([-EXCESO_LONGITUDINAL,-ANCHO_INTERNO_Y/2,SEPARACION_BASE_TUBO+DIAMETRO_TUBO/2])
                cube([LONGITUD_TUBO+2*EXCESO_LONGITUDINAL,ANCHO_INTERNO_Y, ESPESOR_BASE]);
            
            difference() {
                translate([0,-ANCHO_INTERNO_Y/2,DIAMETRO_TUBO/2+SEPARACION_BASE_TUBO-(DIAMETRO_TUBO/2+SEPARACION_BASE_TUBO+DIAMETRO_TUBO)]) {
                    translate([-EXCESO_LONGITUDINAL,0,0])
                        cube([EXCESO_LONGITUDINAL+DISTANCIA_CUBRIR_TUBO,ANCHO_INTERNO_Y,DIAMETRO_TUBO/2+SEPARACION_BASE_TUBO+DIAMETRO_TUBO]);
                    translate([LONGITUD_TUBO+EXCESO_LONGITUDINAL-(EXCESO_LONGITUDINAL+DISTANCIA_CUBRIR_TUBO),0,0])
                        cube([EXCESO_LONGITUDINAL+DISTANCIA_CUBRIR_TUBO,ANCHO_INTERNO_Y,DIAMETRO_TUBO/2+SEPARACION_BASE_TUBO+DIAMETRO_TUBO]);
                }
                translate([-EXCESO_LONGITUDINAL-1,0,0])
                rotate(a=90,v=[0,1,0])
                    cylinder(h=LONGITUD_TUBO+2*EXCESO_LONGITUDINAL+2,d=DIAMETRO_TUBO);
            }
        }
        translate([0,-DIAMETRO_TUBO/2,0]) {
        translate([-EXCESO_LONGITUDINAL,0,0])
            cube([EXCESO_LONGITUDINAL+DISTANCIA_CUBRIR_TUBO/2,DIAMETRO_TUBO,DIAMETRO_TUBO/2+SEPARACION_BASE_TUBO+ESPESOR_BASE]);
        translate([LONGITUD_TUBO+EXCESO_LONGITUDINAL-(EXCESO_LONGITUDINAL+DISTANCIA_CUBRIR_TUBO/2),0,0])
            cube([EXCESO_LONGITUDINAL+DISTANCIA_CUBRIR_TUBO/2,DIAMETRO_TUBO,DIAMETRO_TUBO/2+SEPARACION_BASE_TUBO+ESPESOR_BASE]);
        }
    }
}

module gabinete_tapa() {
    altura_tapa = SEPARACION_BASE_TUBO+3/2*DIAMETRO_TUBO+ESPESOR_BASE+ALTO_INTERNO_Z;
    offset_z = -DIAMETRO_TUBO/2-DIAMETRO_TUBO/2;
    translate([-LUZ_TAPA_BASE-EXCESO_LONGITUDINAL,-LUZ_TAPA_BASE-ANCHO_INTERNO_Y/2-ESPESOR_MINIMO,offset_z])
        cube([2*LUZ_TAPA_BASE+2*EXCESO_LONGITUDINAL+LONGITUD_TUBO,ESPESOR_MINIMO,altura_tapa]);
    translate([-LUZ_TAPA_BASE-EXCESO_LONGITUDINAL,LUZ_TAPA_BASE+ANCHO_INTERNO_Y/2,offset_z])
        cube([2*LUZ_TAPA_BASE+2*EXCESO_LONGITUDINAL+LONGITUD_TUBO,ESPESOR_MINIMO,altura_tapa]);
    translate([-EXCESO_LONGITUDINAL-ESPESOR_MINIMO-LUZ_TAPA_BASE,-LUZ_TAPA_BASE-ANCHO_INTERNO_Y/2-ESPESOR_MINIMO,offset_z])
        cube([ESPESOR_MINIMO,2*LUZ_TAPA_BASE+2*ESPESOR_MINIMO+ANCHO_INTERNO_Y,altura_tapa]);
    translate([LUZ_TAPA_BASE+EXCESO_LONGITUDINAL+LONGITUD_TUBO,-LUZ_TAPA_BASE-ANCHO_INTERNO_Y/2-ESPESOR_MINIMO,offset_z])
        cube([ESPESOR_MINIMO,2*LUZ_TAPA_BASE+2*ESPESOR_MINIMO+ANCHO_INTERNO_Y,altura_tapa]);
    translate((ESPESOR_MINIMO+LUZ_TAPA_BASE)*[-1,-1,0]+[-EXCESO_LONGITUDINAL,-ANCHO_INTERNO_Y/2,offset_z+altura_tapa])
		cube(2*(ESPESOR_MINIMO+LUZ_TAPA_BASE)*[1,1,0]+[2*EXCESO_LONGITUDINAL+LONGITUD_TUBO,ANCHO_INTERNO_Y,ESPESOR_MINIMO]);
}

gabinete_base();
translate([0,0,SEPARACION_BASE_TUBO+DIAMETRO_TUBO/2+ESPESOR_BASE]) {
    translate([POSICION_ARRANCADOR_X,-9/2,0])
        zocalo_con_arrancador();
    translate([POSICION_REACTANCIA_X,-41/2,0])
        reactancia();
}
rotate(a=90, v=[0,1,0])
    tubo_germicida();

color(alpha=.5) gabinete_tapa();
